#pragma once
const int MAX_64BITS = 2147483647;
const int SERVER_PORT = 50000;
const int PLAYER_DESCONNECTION = 30;
const int SERVER_DESCONNECTION = 30;
const float PERCENT_PACKETLOSS = 0.1f;


enum HEADER_PLAYER
{
	HELLO,
	CHALLENGE_R,
	GENERICMSG_P,
	EXIT,
	CRITICALPACKAGE_P,
};

enum HEADER_SERVER
{
	CHALLENGE_Q,
	WELCOME,
	GENERICMSG_S,
	CRITICALPACKAGE_S,
};

enum HEADER_GAMESTATE
{
	
};